const express=require('express');
const session=require('express-session');
const bcrypt=require('bcryptjs');
const {DatabaseSync}=require('node:sqlite');
const fs=require('fs');
const path=require('path');
const app=express();
const PORT=process.env.PORT||3000;
const dataDir=path.join(__dirname,'data'); fs.mkdirSync(dataDir,{recursive:true});
const dbPath=process.env.DB_PATH||path.join(dataDir,'tokyo.db');
const db=new DatabaseSync(dbPath);
db.exec(`
PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'employee',permissions TEXT NOT NULL DEFAULT '{}',phone TEXT DEFAULT '',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT DEFAULT '',address TEXT DEFAULT '',notes TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS contracts(id INTEGER PRIMARY KEY AUTOINCREMENT,customer_id INTEGER NOT NULL,total REAL NOT NULL DEFAULT 0,paid REAL NOT NULL DEFAULT 0,from_date TEXT DEFAULT '',to_date TEXT DEFAULT '',receipt_date TEXT DEFAULT '',notes TEXT DEFAULT '',status TEXT DEFAULT 'جديد',created_by INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS measurements(id INTEGER PRIMARY KEY AUTOINCREMENT,customer_id INTEGER,height REAL DEFAULT 0,details TEXT DEFAULT '',created_by INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS attendance(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,type TEXT NOT NULL,lat REAL,lng REAL,selfie TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS expenses(id INTEGER PRIMARY KEY AUTOINCREMENT,area TEXT NOT NULL DEFAULT 'المعرض',name TEXT NOT NULL,amount REAL NOT NULL DEFAULT 0,expense_date TEXT DEFAULT '',notes TEXT DEFAULT '',created_by INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS factory_jobs(id INTEGER PRIMARY KEY AUTOINCREMENT,customer_id INTEGER,title TEXT NOT NULL,status TEXT DEFAULT 'بانتظار العمل',priority INTEGER DEFAULT 0,materials TEXT DEFAULT '',shortages TEXT DEFAULT '',notes TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS company_notes(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,body TEXT DEFAULT '',urgent INTEGER DEFAULT 0,created_by INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
`);
if(!db.prepare('SELECT id FROM users WHERE username=?').get('admin')){
  db.prepare('INSERT INTO users(name,username,password_hash,role,permissions) VALUES(?,?,?,?,?)').run('مدير النظام','admin',bcrypt.hashSync('Tokyo@2026',10),'admin',JSON.stringify({all:true}));
}
app.use(express.json({limit:'12mb'}));
app.use(express.urlencoded({extended:true}));
app.use(session({secret:process.env.SESSION_SECRET||'tokyo-change-this-secret',resave:false,saveUninitialized:false,cookie:{sameSite:'lax',maxAge:43200000}}));
app.use(express.static(path.join(__dirname,'public')));
const auth=(req,res,next)=>req.session.user?next():res.status(401).json({error:'UNAUTHORIZED'});
const admin=req=>req.session.user?.role==='admin';
const can=(req,p)=>admin(req)||!!(req.session.user?.permissions||{})[p];
const perm=p=>(req,res,next)=>can(req,p)?next():res.status(403).json({error:'FORBIDDEN'});
app.get('/healthz',(req,res)=>res.json({ok:true}));
app.post('/api/login',(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE username=? AND active=1').get(req.body.username);if(!u||!bcrypt.compareSync(req.body.password||'',u.password_hash))return res.status(401).json({error:'اسم المستخدم أو كلمة المرور غير صحيحة'});req.session.user={id:u.id,name:u.name,username:u.username,role:u.role,permissions:JSON.parse(u.permissions||'{}')};res.json(req.session.user)});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/me',auth,(req,res)=>res.json(req.session.user));
app.get('/api/dashboard',auth,(req,res)=>{const c={};for(const t of ['customers','contracts','measurements','factory_jobs','expenses','company_notes'])c[t]=db.prepare(`SELECT COUNT(*) c FROM ${t}`).get().c;const f=db.prepare('SELECT COALESCE(SUM(total),0) total,COALESCE(SUM(paid),0) paid FROM contracts').get();const e=db.prepare('SELECT COALESCE(SUM(amount),0) amount FROM expenses').get().amount;res.json({counts:c,finance:f,expenses:e})});
app.get('/api/search',auth,(req,res)=>{if(!admin(req)&&!can(req,'search'))return res.status(403).json({error:'FORBIDDEN'});const q='%'+(req.query.q||'').trim()+'%';const cs=db.prepare('SELECT * FROM customers WHERE name LIKE ? OR phone LIKE ? OR address LIKE ? ORDER BY id DESC LIMIT 30').all(q,q,q);res.json(cs.map(c=>({...c,contracts:db.prepare('SELECT * FROM contracts WHERE customer_id=? ORDER BY id DESC').all(c.id),measurements:db.prepare('SELECT * FROM measurements WHERE customer_id=? ORDER BY id DESC').all(c.id),factory:db.prepare('SELECT * FROM factory_jobs WHERE customer_id=? ORDER BY id DESC').all(c.id)})))});
app.get('/api/customers',auth,(req,res)=>res.json(db.prepare('SELECT * FROM customers ORDER BY id DESC').all()));
app.post('/api/customers',auth,perm('customers'),(req,res)=>{const b=req.body;const r=db.prepare('INSERT INTO customers(name,phone,address,notes) VALUES(?,?,?,?)').run(b.name,b.phone||'',b.address||'',b.notes||'');res.json({id:Number(r.lastInsertRowid)})});
app.get('/api/contracts',auth,perm('contracts'),(req,res)=>res.json(db.prepare(`SELECT contracts.*,customers.name customer_name,customers.phone,customers.address FROM contracts JOIN customers ON customers.id=contracts.customer_id ORDER BY contracts.id DESC`).all()));
app.post('/api/contracts',auth,perm('contracts'),(req,res)=>{const b=req.body;const r=db.prepare('INSERT INTO contracts(customer_id,total,paid,from_date,to_date,receipt_date,notes,status,created_by) VALUES(?,?,?,?,?,?,?,?,?)').run(b.customer_id,+b.total||0,+b.paid||0,b.from_date||'',b.to_date||'',b.receipt_date||'',b.notes||'',b.status||'جديد',req.session.user.id);res.json({id:Number(r.lastInsertRowid)})});
app.get('/api/measurements',auth,perm('measurements'),(req,res)=>res.json(db.prepare(`SELECT measurements.*,customers.name customer_name FROM measurements LEFT JOIN customers ON customers.id=measurements.customer_id ORDER BY measurements.id DESC`).all()));
app.post('/api/measurements',auth,perm('measurements'),(req,res)=>{const b=req.body;const r=db.prepare('INSERT INTO measurements(customer_id,height,details,created_by) VALUES(?,?,?,?)').run(b.customer_id||null,+b.height||0,b.details||'',req.session.user.id);res.json({id:Number(r.lastInsertRowid)})});
app.get('/api/attendance',auth,(req,res)=>{if(admin(req)||can(req,'attendance_all'))return res.json(db.prepare(`SELECT attendance.*,users.name user_name FROM attendance JOIN users ON users.id=attendance.user_id ORDER BY attendance.id DESC LIMIT 300`).all());res.json(db.prepare('SELECT * FROM attendance WHERE user_id=? ORDER BY id DESC LIMIT 100').all(req.session.user.id))});
app.post('/api/attendance',auth,(req,res)=>{const b=req.body;if(!['in','out'].includes(b.type))return res.status(400).json({error:'BAD_TYPE'});db.prepare('INSERT INTO attendance(user_id,type,lat,lng,selfie) VALUES(?,?,?,?,?)').run(req.session.user.id,b.type,b.lat||null,b.lng||null,b.selfie||'');res.json({ok:true})});
app.get('/api/expenses',auth,perm('expenses'),(req,res)=>res.json(db.prepare('SELECT * FROM expenses ORDER BY id DESC').all()));
app.post('/api/expenses',auth,perm('expenses'),(req,res)=>{const b=req.body;db.prepare('INSERT INTO expenses(area,name,amount,expense_date,notes,created_by) VALUES(?,?,?,?,?,?)').run(b.area||'المعرض',b.name,+b.amount||0,b.expense_date||'',b.notes||'',req.session.user.id);res.json({ok:true})});
app.get('/api/factory',auth,perm('factory'),(req,res)=>res.json(db.prepare(`SELECT factory_jobs.*,customers.name customer_name FROM factory_jobs LEFT JOIN customers ON customers.id=factory_jobs.customer_id ORDER BY priority DESC,id DESC`).all()));
app.post('/api/factory',auth,perm('factory'),(req,res)=>{const b=req.body;db.prepare('INSERT INTO factory_jobs(customer_id,title,status,priority,materials,shortages,notes) VALUES(?,?,?,?,?,?,?)').run(b.customer_id||null,b.title,b.status||'بانتظار العمل',+b.priority||0,b.materials||'',b.shortages||'',b.notes||'');res.json({ok:true})});
app.get('/api/notes',auth,(req,res)=>res.json(db.prepare('SELECT * FROM company_notes ORDER BY urgent DESC,id DESC').all()));
app.post('/api/notes',auth,perm('notes'),(req,res)=>{db.prepare('INSERT INTO company_notes(title,body,urgent,created_by) VALUES(?,?,?,?)').run(req.body.title,req.body.body||'',req.body.urgent?1:0,req.session.user.id);res.json({ok:true})});
app.get('/api/users',auth,(req,res)=>admin(req)?res.json(db.prepare('SELECT id,name,username,role,permissions,phone,active,created_at FROM users ORDER BY id DESC').all()):res.status(403).json({error:'FORBIDDEN'}));
app.post('/api/users',auth,(req,res)=>{if(!admin(req))return res.status(403).json({error:'FORBIDDEN'});const b=req.body;try{const r=db.prepare('INSERT INTO users(name,username,password_hash,role,permissions,phone) VALUES(?,?,?,?,?,?)').run(b.name,b.username,bcrypt.hashSync(b.password||'12345678',10),b.role||'employee',JSON.stringify(b.permissions||{}),b.phone||'');res.json({id:Number(r.lastInsertRowid)})}catch(e){res.status(400).json({error:'اسم المستخدم موجود مسبقًا'})}});
app.listen(PORT,'0.0.0.0',()=>{console.log(`TOKYO Management running on http://0.0.0.0:${PORT}`);console.log(`Database: ${dbPath}`)});
